# Generated by Django 4.1.1 on 2022-11-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Spreads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("homeTeam", models.CharField(max_length=200)),
                ("awayTeam", models.CharField(max_length=200)),
                ("bookmaker", models.CharField(max_length=200)),
                ("commenceTime", models.DateTimeField()),
                ("lastUpdated", models.DateTimeField()),
                ("gameID", models.CharField(max_length=200)),
                ("homePoints", models.FloatField()),
                ("homePrice", models.IntegerField()),
                ("awayPoints", models.FloatField()),
                ("awayPrice", models.IntegerField()),
            ],
        ),
    ]
