# Generated by Django 4.1.1 on 2022-11-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oddsAndEvents", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="spreads",
            unique_together={
                ("homeTeam", "awayTeam", "bookmaker", "commenceTime", "lastUpdated")
            },
        ),
        migrations.CreateModel(
            name="Totals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("homeTeam", models.CharField(max_length=200)),
                ("awayTeam", models.CharField(max_length=200)),
                ("bookmaker", models.CharField(max_length=200)),
                ("commenceTime", models.DateTimeField()),
                ("lastUpdated", models.DateTimeField()),
                ("gameID", models.CharField(max_length=200)),
                ("overPoints", models.FloatField()),
                ("overPrice", models.IntegerField()),
                ("underPoints", models.FloatField()),
                ("underPrice", models.IntegerField()),
            ],
            options={
                "unique_together": {
                    ("homeTeam", "awayTeam", "bookmaker", "commenceTime", "lastUpdated")
                },
            },
        ),
        migrations.CreateModel(
            name="Moneyline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("homeTeam", models.CharField(max_length=200)),
                ("awayTeam", models.CharField(max_length=200)),
                ("bookmaker", models.CharField(max_length=200)),
                ("commenceTime", models.DateTimeField()),
                ("lastUpdated", models.DateTimeField()),
                ("gameID", models.CharField(max_length=200)),
                ("homePrice", models.IntegerField()),
                ("awayPrice", models.IntegerField()),
            ],
            options={
                "unique_together": {
                    ("homeTeam", "awayTeam", "bookmaker", "commenceTime", "lastUpdated")
                },
            },
        ),
    ]
